# Restaurant Recommendation System

## Objective
The objective of this project is to build a restaurant recommendation system that suggests restaurants based on user preferences such as cuisine, city, and price range.

### Techniques Used
- Content-Based Filtering
- CountVectorizer
- Cosine Similarity

### Expected Output
The system recommends restaurants that are similar to the user's preferences.

In [ ]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv("Dataset .csv")

In [3]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
df.shape

(9551, 21)

In [5]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [7]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [8]:
df["Cuisines"] = df["Cuisines"].fillna("Unknown")

In [9]:
df["City"] = df["City"].fillna("Unknown")

In [13]:
data = df[[
    "Restaurant Name",
    "Cuisines",
    "Average Cost for two",
    "Price range",
    "Aggregate rating",
    "City"
]].copy()

In [14]:
data.head()

,Restaurant Name,Cuisines,Average Cost for two,Price range,Aggregate rating,City
0,Le Petit Souffle,"French, Japanese, Desserts",1100,3,4.8,Makati City
1,Izakaya Kikufuji,Japanese,1200,3,4.5,Makati City
2,Heat - Edsa Shangri-La,"Seafood, Asian, Filipino, Indian",4000,4,4.4,Mandaluyong City
3,Ooma,"Japanese, Sushi",1500,4,4.9,Mandaluyong City
4,Sambo Kojin,"Japanese, Korean",1500,4,4.8,Mandaluyong City

In [15]:
data["features"] = (
    data["Cuisines"].astype(str) + " " +
    data["City"].astype(str) + " " +
    data["Price range"].astype(str)
)

In [16]:
data[["Restaurant Name", "features"]].head()

          Restaurant Name                                           features
0        Le Petit Souffle           French, Japanese, Desserts Makati City 3
1        Izakaya Kikufuji                             Japanese Makati City 3
2  Heat - Edsa Shangri-La  Seafood, Asian, Filipino, Indian Mandaluyong C...
3                    Ooma                 Japanese, Sushi Mandaluyong City 4
4             Sambo Kojin                Japanese, Korean Mandaluyong City 4

In [17]:
cv = CountVectorizer(stop_words="english")

In [18]:
matrix = cv.fit_transform(data["features"])

In [19]:
similarity = cosine_similarity(matrix)

In [20]:
similarity.shape

(9551, 9551)

In [ ]:
def recommend_restaurant(cuisine, city, price_range):

    
    filtered_data = data[
        (data["City"].str.lower() == city.lower()) &
        (data["Price range"] == price_range)
    ]

    
    if filtered_data.empty:
        return "No restaurants found matching your criteria."


    filtered_features = filtered_data["features"]


    filtered_matrix = cv.transform(filtered_features)

    user_input = cuisine + " " + city + " " + str(price_range)


    user_vector = cv.transform([user_input])

    scores = cosine_similarity(user_vector, filtered_matrix)

    scores = scores.flatten()


    top_indexes = scores.argsort()[::-1][:10]

    
    recommendations = filtered_data.iloc[top_indexes][[
        "Restaurant Name",
        "Cuisines",
        "City",
        "Price range",
        "Aggregate rating"
    ]]

    recommendations = recommendations[
        recommendations["Aggregate rating"] > 3.5
    ]

    recommendations = recommendations.drop_duplicates(
        subset="Restaurant Name"
    )

    
    recommendations = recommendations.sort_values(
        by="Aggregate rating",
        ascending=False
    )

    return recommendations

In [28]:
recommend_restaurant(
    cuisine="North Indian",
    city="New Delhi",
    price_range=2
)

     Restaurant Name      Cuisines       City  Price range  Aggregate rating
6758    Satvik Rasoi  North Indian  New Delhi            2               3.8

In [29]:
recommend_restaurant(
    cuisine="Chinese",
    city="Mumbai",
    price_range=3
)

,Restaurant Name,Cuisines,City,Price range,Aggregate rating
2483,The Fusion Kitchen,"North Indian, Italian, Chinese, Mexican",Mumbai,3,4.7
2489,Farzi Cafe,Modern Indian,Mumbai,3,4.3
2490,SpiceKlub,North Indian,Mumbai,3,4.2
2481,Cafe Hydro,Asian,Mumbai,3,4.0
2496,38 Degree East,"North Indian, Chinese, Thai",Mumbai,3,3.8
2487,Mumbai Vibe,"Cafe, Continental, North Indian, Italian, Chin...",Mumbai,3,3.8
2499,Tea Villa Cafe,"Cafe, Italian, Desserts, Fast Food, Chinese, Tea",Mumbai,3,3.6

In [33]:
recommend_restaurant(
    cuisine="Fast Food",
    city="Noida",
    price_range=2
)

     Restaurant Name   Cuisines   City  Price range  Aggregate rating
8447      McDonald's  Fast Food  Noida            2               3.9
8251  Being Truckers  Fast Food  Noida            2               3.8

In [34]:
cuisine = input("Enter Cuisine: ")
city = input("Enter City: ")
price = int(input("Enter Price Range (1-4): "))

recommend_restaurant(cuisine, city, price)

,Restaurant Name,Cuisines,City,Price range,Aggregate rating
8354,DIOS The Neighbourhood Bistro,"Continental, Fast Food, Italian",Noida,3,4.2
8061,Pizza Hut,"Italian, Pizza, Fast Food",Noida,3,3.9
8428,Bikanervala Bliss,"North Indian, Fast Food, Chinese",Noida,3,3.6

# Conclusion

A content-based restaurant recommendation system was successfully developed using restaurant features such as cuisine, city, and price range.

CountVectorizer was used for text vectorization, while Cosine Similarity was used to identify similar restaurants. The system provides personalized restaurant recommendations based on user preferences.